### ISSUE TITLE
 a plugin with this name ('LinkPlugin') is already registered

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [django-cms/djangocms-frontend#38]
**Describe the bug**
Attempt to migrate from bs4 to frontend

```
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/djangocms_frontend/contrib/carousel/cms_plugins.py", line 10, in <module>
    from ..link.cms_plugins import LinkPluginMixin
  File "/usr/local/lib/python3.9/site-packages/djangocms_frontend/contrib/link/cms_plugins.py", line 89, in <module>
    class LinkPlugin(
  File "/usr/local/lib/python3.9/site-packages/cms/plugin_pool.py", line 117, in register_plugin
    raise PluginAlreadyRegistered(
cms.exceptions.PluginAlreadyRegistered: Cannot register <class 'djangocms_frontend.contrib.link.cms_plugins.LinkPlugin'>, a plugin with this name ('LinkPlugin') is already registered.
```

commenting in settings.py djangocms_link
result : 

```
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/djangocms_bootstrap4/contrib/bootstrap4_carousel/models.py", line 9, in <module>
    from djangocms_link.models import AbstractLink
  File "/usr/local/lib/python3.9/site-packages/djangocms_link/models.py", line 268, in <module>
    class Link(AbstractLink):
  File "/usr/local/lib/python3.9/site-packages/cms/models/pluginmodel.py", line 78, in __new__
    new_class = super_new(cls, name, bases, attrs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 113, in __new__
    raise RuntimeError(
RuntimeError: Model class djangocms_link.models.Link doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```

**To Reproduce**
1. install all needed modules 
2. Add djangocms_frontend .... modules to settings.py
3. Keep bootstrap in settings.py like recommended in migration docs.

**Expected behavior**
At least have to work

**Additional context**

beside this frontend also block execution of command `python manage.py collectstatic --noinput`
So it is not possible anymore to build image with : 

```
FROM python:3.9
WORKDIR /app
COPY . /app
RUN pip install -r requirements.txt
RUN python manage.py collectstatic --noinput
CMD uwsgi --http=0.0.0.0:80 --module=backend.wsgi
```

**Comment by fsbraun** [comment]
@jpVm5jYYRE1VIKL Thanks for reporting this!

Indeed the documentation is not clear enough on it: The djangocms_frontend packages need to go **after** the djangocms_bootstrap4 packages. Djangocms_bootstrap4 depends on djangocms_link (which has to be before the djangocms_bootstrap4 packages). Hence, for you the order in `settings.py` should be 

```
INSTALLED_APPS = [
    ...,
    "djangocms_link",
    "djangocms_bootstrap4",
    "djangocms_bootstrap4.contrib.bootstrap4_utilities",
    "djangocms_bootstrap4.contrib.bootstrap4_tabs",
    "djangocms_bootstrap4.contrib.bootstrap4_grid",
    "djangocms_bootstrap4.contrib.bootstrap4_alerts",
    "djangocms_bootstrap4.contrib.bootstrap4_card",
    "djangocms_bootstrap4.contrib.bootstrap4_listgroup",
    "djangocms_bootstrap4.contrib.bootstrap4_badge",
    "djangocms_bootstrap4.contrib.bootstrap4_link",
    "djangocms_bootstrap4.contrib.bootstrap4_collapse",
    "djangocms_bootstrap4.contrib.bootstrap4_content",
    "djangocms_bootstrap4.contrib.bootstrap4_media",
    "djangocms_bootstrap4.contrib.bootstrap4_jumbotron",
    "djangocms_bootstrap4.contrib.bootstrap4_picture",
    "djangocms_bootstrap4.contrib.bootstrap4_carousel",
    "djangocms_frontend",
    "djangocms_frontend.contrib.utilities",
    "djangocms_frontend.contrib.tabs",
    "djangocms_frontend.contrib.grid",
    "djangocms_frontend.contrib.alert",
    "djangocms_frontend.contrib.card",
    "djangocms_frontend.contrib.listgroup",
    "djangocms_frontend.contrib.badge",
    "djangocms_frontend.contrib.link",
    "djangocms_frontend.contrib.collapse",
    "djangocms_frontend.contrib.content",
    "djangocms_frontend.contrib.media",
    "djangocms_frontend.contrib.jumbotron",
    "djangocms_frontend.contrib.image",
    "djangocms_frontend.contrib.carousel",
    "djangocms_frontend.contrib.accordion",
    "djangocms_frontend.contrib.frontend_forms",
    ...,
]

```

After migrating, both the `djangocms_link` and the `djangocms_bootstrap4` entries can go.

Let me know if reordering helped. I will update the docs.

**Comment by jpVm5jYYRE1VIKL** [comment]
Hi. Yes change of order helped a lot and image generated and passed. But most probably migration procedire have to be adjusted. My project widely use card decks due to it get :
```
Migrating plugins
=================
* Detected bootstrap v4 card-deck which is not part of bootstrap5
  Replaced it with Card Layout, grid cards
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "djangocms_frontend_frontenduiitem" does not exist
LINE 1: UPDATE "djangocms_frontend_frontenduiitem" SET "ui_item" = '...
```
may be advice how better to migrate. may be something semi automatic. I have more than hundred card decks.

**Comment by fsbraun** [comment]
Again, this is a good hint: `./manage.py frontend migrate` might check if the database migrations have been run!

**Comment by fsbraun** [comment]
What database are you using? This sql delete statement removes the migrated plugin from the database.

The migration process will create rows and columns that hold the cards. You will find a CardLayoutPlugin which you can change if you want.

**Comment by fsbraun** [comment]
Alternatively, you can try the hot fix by installing `pip install git+https://github.com/fsbraun/djangocms-frontend@fix/migration#egg=djangocms-frontend` .

**Comment by jpVm5jYYRE1VIKL** [comment]
I made it to work with this : 
```

                with connection.cursor() as cursor:
                    cursor.execute(
                        f'DELETE FROM "{obj._meta.db_table}" WHERE cmsplugin_ptr_id={obj.id};'
                    )
```
changed general statement to singlequote and inside set doublequote.

**Comment by fsbraun** [comment]
Great! I will prepare a PR to fix this (depending on the database used). Did it run through now?

**Comment by jpVm5jYYRE1VIKL** [comment]
yes with code i showed it passed . Thanks for your help.

**Comment by fsbraun** [comment]
Pleasure! Thanks for pointing out these issues!

**Comment by jpVm5jYYRE1VIKL** [comment]
I looked on PR and I think that usage only **"** in statement will break something. I have feeling that python will generate syntax error because will detect it as two separate strings  `"DELETE FROM  "` and `" WHERE cmsplugin_ptr_id={obj.id};'"`

**Comment by fsbraun** [comment]
Hold on, the PR should look like this: https://github.com/django-cms/djangocms-frontend/blob/07160bf04549395f3db9b56c4566f8e62af9e45d/djangocms_frontend/management/commands/subcommands/migrate.py#L95-L100
🤔

mysql needs the backtick (at least if it is not running in ansi mode which is not the standard).

**Comment by jpVm5jYYRE1VIKL** [comment]
Yes you right. Sorry.

**Comment by fsbraun** [comment]
It's always good to have at least two more eyes looking at the code! Thank you for your time!
